### ISSUE TITLE
RFCxxx Trusted connections

### ISSUE THREAD

**Issue by woutslakhorst** [nuts-foundation/nuts-specification#135]
Trusted connections are required for private credential transport.

In a full mesh network, 1 connection between 2 nodes is enough. An incomming connection is anonymous at first (since the only thing you know about is is the IP). A node can not use this connection to send VCs to. It must be upgraded to a _trusted connection_.

The basic requirements:

- A DID (of a care organization) must be resolvable to an established connection (in a full-mesh network).
- A handshake needs to take place over a live connection. This will make certain DIDs known at both sides of the connection
- These DIDs are not the care organisation DIDs, so the care organization DID will have to be linked to the "connection DID"

The last requirement really boils down to private key ownage. The entity that owns both the connection DID and the care organization DID must supply this link.

proposed solution:
Each care organization DID will list a _NutsComm_ endpoint that refers to a _NutsComm_ endpoint on the vendor DID Document. That way all serviced customers can reuse a single endpoint. This will also solve discoverability.
When a new connection is made, both sides can add a challenge to the connection _headers_. This challenge can then be signed by the vendor (using its assertionMethod key). The return message will be a custom protocol message. When received by one side of the connection, the receiver can verify the signature and mark the subject at the other end connection with a certain DID. Connections that are marked with a DID can then be matched against the DID in the endpoint reference of a care organization DID Document. The message with the signature can be sent at any time while the connection is live. Only after the message has been verified will make the connection trusted.

definition:
a trusted connection is a connection that has received a signature to a challenge from a DID and that DID has a NutsComm service endpoint in its DID Document.

**Comment by woutslakhorst** [comment]
One important part of a design decision could be that a node should not be able to read encrypted data (node as a service model)

**Comment by reinkrul** [comment]
I vision that the "trusted" or "authenticated" state of a connection is just a flag: when required (because a node wants to exchange some data that requires an authenticated connection) it can upgrade it by sending an authentication challenge. When that succeeds it can send the sensitive data. It means that in case there already is a connection to the particular party (which is being used for DAG sync, e.g.) it can be reused (or better "upgraded").

Could be the peer's DID (the one that needs to be authenticated) and some random data (to avoid replay attacks, determine what's a good length) that has to be signed by the peer with a specific `verificationMethod` key from the DID's document using `ChallengeRequest`. The peer then signs the challenge and responds with `ChallengeResponse`, which is checked by the sender.

But maybe the mixing of layers here could be problematic? (network layer depends on specific keys/IDs from VDR layer)

**Comment by woutslakhorst** [comment]
Fixed by RFC015?
