### ISSUE TITLE
RFC004: extend transaction format with `to`

### ISSUE THREAD

**Issue by woutslakhorst** [nuts-foundation/nuts-specification#155]

**Comment by reinkrul** [comment]
The `to` header is used to address a TX to a specific recipient. The header must be encrypted, so the receiver can remain anonymous (correlation attack mitigation).

This, however, leads to the following 2 issues to solve:

- When the intended receiver comes back to the sender to query the TX payload, how does the sender know `receiver == encrypted_to`? The receiver is identified and authenticated with `node DID`, but since the `to` header is encrypted there's no way to match it with the TX.
- How do Nuts nodes running in a cluster assure the private TX payload is available to all cluster members (assuming that the receiver's payload query can be handled by any cluster member).

**Comment by woutslakhorst** [comment]
The current view on future clustering is that the DAG is our transaction log and that we use grpc for syncing the data between nodes. If we keep doing this, we cannot introduce a storage layer that would require clustering when multiple nodes per vendor exist. This would be required when the ACL is only stored locally. Therefore the last option would be the only feasible one.

**Comment by reinkrul** [comment]
We could have a single list of recipients, not separated/annotated with the actual receiver or sender. Or we could have separate headers for that.

**Comment by woutslakhorst** [comment]
`to` and `from` would be weird names when data is shared between clustered nodes.
