### ISSUE TITLE
RFC017: Gossip TX ref contents should prevent certain attacks but doesn't

### ISSUE THREAD

**Issue by woutslakhorst** [nuts-foundation/nuts-specification#163]
The current Gossip message is specified to only contain the *own* transactions of a node not other TXs. Part of the idea was that if a Node created a TX way in the past that the set reconciliation would take ages but that afterwards other nodes would quickly pick it up via the Gossip protocol.

**Comment by woutslakhorst** [comment]
One solution is to change the spec that the gossip message does contain all TXs newly added to the DAG. This list can then be filtered based on incoming Gossip messages. If A gossips [1, 2, 3] to B and B was going to Gossip [1, 2, 3, 4]. Then B removes t to 3 from the list and only Gossips [4] to A. This tracking of TX's has to be done per connection.

**Comment by gerardsn** [comment]
The specs are inconsistent on what transactions should be included in the Gossip message. From the second paragraph in §5.2.1 (with some highlighting):
> The `Gossip` message MUST contain an `XOR` value, an `LC` value and a list of transaction references (`transactions`). The list MUST contain **transaction references added to the DAG** since the last `Gossip` message. The list of transaction references MUST be tracked per connection. If no new transactions have been added/**received** or for the first message for a connection, an empty list is sent. 

Based on the above and the discussions in #159 I assumed that the Gossip message contained _all_ transactions added to the DAG since the previous Gossip.

A peer specific Gossip list is cleaner, but I don't see any issues leaving this out initially.

**Comment by woutslakhorst** [comment]
So proposal:

A: make it more clear that we mean ALL transactions
B: add a SHOULD directive to filter out any TX already received by the peer in the context of a connection.
