### ISSUE TITLE
RFC017 §3 disconnect on node authentication is incorrect

### ISSUE THREAD

**Issue by woutslakhorst** [nuts-foundation/nuts-specification#252]
With dynamic discovery enabled, it won't be possible for a node to connect to a bootstrap node that changed its NodeDID somewhere in time.

The new node is synchronizing transactions and somewhere it gets the first (outdated) NutsComm address. Auto discovery will update and then try to reconnect/reauthenticate. This will fail, it should continue with connecting and fetch transactions.

Disconnect on failed authentication should be changed.

**Comment by woutslakhorst** [comment]
@gerardsn

**Comment by gerardsn** [comment]
We could add a bootstrap flow:
A node does not send its DID to the peer it wants to have a bootstrap connection with, and it ignores the DID received from the bootstrap node. This way the connection is anonymous (peer's DID is unknown) and therefor unauthenticated on both sides. Since this connection only uses an address, it is not affected by DID updates / dynamic service discovery.

The nodes can setup another connection that is authenticated for private VC exchange.
